export const GET_CONTACTS_STARTED = "GET_CONTACTS_STARTED";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILED = "GET_CONTACTS_FAILED";

export const TOOGLE_TRUE = "TOOGLE_TRUE";
export const TOOGLE_FALSE = "TOOGLE_FALSE";
export const GET_CONTACT = "GET_CONTACT";
export const POST_CONTACT = "POST_CONTACT";
